### ISSUE TITLE
issue with SCNIC between

### ISSUE THREAD

**Issue by sudhiron11** [shafferm/SCNIC#26]
Hey..
I am running SCNIC to create network between two different tables (bacterial and fungal abundances).
I am using SCNIC between (SCNIC_analysis.py between ). Every time I run into this error.
I also tried q2 plugin, which is also running into something similar.
Can you please help me.

Thank you in advance!!

I am pasting the command and the error here: 
(SCNIC) [sudhir@localhost BETWEEN_CORR]$ SCNIC_analysis.py between -1  BACTERIA_6_OUT/feature-table.biom -2 FUNGAL_6_OUT/feature-table.biom -o BETWEEN_CORRELATION
Traceback (most recent call last):
  File "/home/sudhir/miniconda3/envs/SCNIC/bin/SCNIC_analysis.py", line 81, in <module>
    main()
  File "/home/sudhir/miniconda3/envs/SCNIC/bin/SCNIC_analysis.py", line 77, in main
    args.func(**args_dict)

**Comment by sterrettJD** [comment]
Hey @sudhiron11 , if you're still running into this issue, what version of SCNIC are you using? It turns out that the most recent updates had not pushed to PyPI or conda, but it should work now. Can you try with SCNIC v0.6.6?

Thanks,
John
